export const Permissions: { [key: string]: string } = {
  USERS_GET: 'users.get',
  USERS_PUT: 'users.put',
  RESTAURANTS_POST: 'restaurants.post',
  RESTAURANTS_PUT: 'restaurants.put',
  CATALOG_CATEGORIES_POST: 'catalog.categories.post',
  CATALOG_CATEGORIES_PUT: 'catalog.categories.put',
  CATALOG_INGREDIENTS_GET: 'catalog.ingredients.get',
  CATALOG_INGREDIENTS_POST: 'catalog.ingredients.post',
  CATALOG_INGREDIENTS_PUT: 'catalog.ingredients.put',
  CATALOG_PRODUCTS_POST: 'catalog.products.post',
  CATALOG_PRODUCTS_PUT: 'catalog.products.put',
  CATALOG_PRODUCTS_INGREDIENTS_GET: 'catalog.products.ingredients.get',
  CATALOG_PRODUCTS_INGREDIENTS_POST: 'catalog.products.ingredients.post',
  CATALOG_PRODUCTS_INGREDIENTS_PUT: 'catalog.products.ingredients.put',
  CATALOG_PRODUCTS_INGREDIENTS_DELETE: 'catalog.products.ingredients.delete',
  ADDRESSES_ALL: 'addresses.all',
  DELIVERIES_POST: 'deliveries.post',
  DELIVERIES_GET: 'deliveries.get',
  DELIVERIES_PATCH: 'deliveries.patch',
  BASKET_GET: 'basket.get',
  BASKET_POST: 'basket.post',
  BASKET_DELETE: 'basket.delete',
} as const
