import { Roles } from 'App/Enums/Roles'
import { Permissions } from 'App/Enums/Permissions'

export const RolesPermissions: { [key: string]: string[] } = {
  [Roles.ADMIN]: [...Object.values(Permissions)],
  [Roles.MANAGER]: [
    Permissions.USERS_GET,
    Permissions.CATALOG_CATEGORIES_POST,
    Permissions.CATALOG_CATEGORIES_PUT,
    Permissions.CATALOG_INGREDIENTS_GET,
    Permissions.CATALOG_INGREDIENTS_POST,
    Permissions.CATALOG_INGREDIENTS_PUT,
    Permissions.CATALOG_PRODUCTS_GET,
    Permissions.CATALOG_PRODUCTS_POST,
    Permissions.CATALOG_PRODUCTS_PUT,
    Permissions.CATALOG_PRODUCTS_INGREDIENTS_GET,
    Permissions.CATALOG_PRODUCTS_INGREDIENTS_POST,
    Permissions.CATALOG_PRODUCTS_INGREDIENTS_PUT,
    Permissions.CATALOG_PRODUCTS_INGREDIENTS_DELETE,
    Permissions.ADDRESSES_ALL,
    Permissions.DELIVERIES_GET,
    Permissions.DELIVERIES_ALL,
    Permissions.BASKET_GET,
    Permissions.BASKET_POST,
    Permissions.BASKET_DELETE,
    Permissions.BASKET_CLEAR,
    Permissions.ORDERS_GET,
    Permissions.ORDERS_POST,
    Permissions.MANAGER_ORDERS_GET,
    Permissions.PROVIDERS_ALL,
    Permissions.MARKETING_GET,
  ],
  [Roles.DELIVERER]: [
    Permissions.ADDRESSES_ALL,
    Permissions.DELIVERIES_GET,
    Permissions.DELIVERIES_ALL,
    Permissions.DELIVERIES_TAKE,
    Permissions.DELIVERIES_COMPLETE,
    Permissions.BASKET_GET,
    Permissions.BASKET_POST,
    Permissions.BASKET_DELETE,
    Permissions.BASKET_CLEAR,
    Permissions.ORDERS_GET,
    Permissions.ORDERS_POST,
  ],
  [Roles.CUSTOMER]: [
    Permissions.ADDRESSES_ALL,
    Permissions.DELIVERIES_GET,
    Permissions.BASKET_GET,
    Permissions.BASKET_POST,
    Permissions.BASKET_DELETE,
    Permissions.BASKET_CLEAR,
    Permissions.ORDERS_GET,
    Permissions.ORDERS_POST,
    Permissions.DELIVERIES_GET,
  ],
}
