apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-auth-config
  labels:
    app: ms-auth
data:
  PORT: '3333'
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DRIVE_DISK: 'local'
  DB_CONNECTION: 'pg'
  PG_HOST: 'ms-auth-db'
  PG_PORT: '5432'
  PG_USER: 'api'
  PG_PASSWORD: 'postgres123'
  PG_DB_NAME: 'ms-auth'
  REDIS_CONNECTION: 'local'
  REDIS_HOST: 'ms-auth-cache'
  REDIS_PORT: '6379'
  RABBITMQ_HOSTNAME: 'event-bus'
  RABBITMQ_PORT: '5672'
  RABIITMQ_PROTOCOL: 'ampq://'
